services:
  - type: web
    name: ai-text-analysis-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    region: oregon
    branch: main
    autoDeploy: true
